version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  dagster:
    build: .
    command: dagster dev -h 0.0.0.0
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db


volumes:
  database_data: {}
